# Generated by Django 5.2.4 on 2025-12-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogsnet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frog",
            name="avatar",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
