# Generated by Django 5.2.4 on 2025-12-02 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogsnet", "0003_frog_friends_alter_frog_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frog",
            name="friends",
        ),
        migrations.AddField(
            model_name="frog",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="frog",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("ingame", "In Game"),
                    ("offline", "Offline"),
                ],
                default="offline",
                max_length=255,
            ),
        ),
    ]
