# Generated by Django 5.2.4 on 2025-12-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frogsnet", "0004_remove_frog_friends_frog_following_frog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="frog",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="frog",
            name="minecraft_username",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
