# Generated by Django 6.1.1 on 2026-09-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0005_frog_last_active_frog_minecraft_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='tier',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
