# Generated by Django 6.1.1 on 2026-09-15 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0006_frog_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frog',
            name='tier',
        ),
        migrations.CreateModel(
            name='DonoSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('frog', 'Frog'), ('scavenger', 'Scavenger'), ('operative', 'Operative'), ('overseer', 'Overseer')], default='frog', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_renewed', models.DateTimeField(auto_now=True)),
                ('frog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='frogsnet.frog')),
            ],
        ),
    ]
