# Generated by Django 6.1.1 on 2026-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0007_remove_frog_tier_donosubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='tier',
            field=models.CharField(blank=True, choices=[('frog', 'Frog'), ('scavenger', 'Scavenger'), ('operative', 'Operative'), ('overseer', 'Overseer')], default='frog', max_length=255),
        ),
        migrations.DeleteModel(
            name='DonoSubscription',
        ),
    ]
