# Generated by Django 6.1.1 on 2026-09-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0008_frog_tier_delete_donosubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
