# Generated by Django 6.1.1 on 2026-09-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0010_forumtopic_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
