# Generated by Django 6.1.1 on 2026-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0011_frog_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frog',
            name='status',
        ),
        migrations.AddField(
            model_name='frog',
            name='in_game_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
