# Generated by Django 6.1.1 on 2026-09-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0012_remove_frog_status_frog_in_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='show_real_name',
            field=models.BooleanField(default=False),
        ),
    ]
