# Generated by Django 6.1.1 on 2026-09-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_modpack'),
        ('frogsnet', '0013_frog_show_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='modpacks',
            field=models.ManyToManyField(blank=True, related_name='players', to='base.modpack'),
        ),
        migrations.CreateModel(
            name='ModpackStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime', models.DurationField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('frog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modpack_stats', to='frogsnet.frog')),
                ('modpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='base.modpack')),
            ],
        ),
    ]
