# Generated by Django 6.1.1 on 2026-09-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0016_friendrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='owner_if_wall',
            field=models.OneToOneField(blank=True, help_text='If this is a user wall, the owner of the wall. Using OneToOne so `user.wall` returns a single topic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wall', to=settings.AUTH_USER_MODEL),
        ),
    ]
