# Generated by Django 6.1.1 on 2026-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0017_alter_forumtopic_owner_if_wall'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
