# Generated by Django 6.1.1 on 2026-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0018_frog_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frog',
            name='last_activity',
        ),
        migrations.AlterField(
            model_name='frog',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
