# Generated by Django 6.1.1 on 2026-09-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0019_remove_frog_last_activity_alter_frog_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='frog',
            name='allow_external_wall_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frog',
            name='allow_friend_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frog',
            name='show_achievements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frog',
            name='show_active_modpacks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frog',
            name='show_last_played_server',
            field=models.BooleanField(default=True),
        ),
    ]
