# Generated by Django 6.1.1 on 2026-09-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0020_frog_allow_external_wall_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frog',
            name='bio',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
