# Generated by Django 6.1.1 on 2026-09-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0021_alter_frog_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='author',
        ),
    ]
