# Generated by Django 6.1.1 on 2026-09-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0023_remove_forumpost_blogpost_ptr_forumpost_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frog',
            name='show_real_name',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('squad_only', 'SQUAD_ONLY'), ('classified', 'CLASSIFIED')], default='public', max_length=20),
        ),
    ]
