# Generated by Django 6.1.1 on 2026-09-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frogsnet', '0026_alter_friendrequest_from_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
