# Generated by Django 5.1.5 on 2025-01-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eng_title', models.CharField(max_length=50)),
                ('eng_markdown_post_text', models.TextField()),
                ('ukr_title', models.CharField(max_length=50)),
                ('ukr_markdown_post_text', models.TextField()),
                ('image', models.ImageField(upload_to='files/blogpost_covers')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('eng_title', models.CharField(max_length=50)),
                ('ukr_title', models.CharField(max_length=50)),
                ('category', models.SmallIntegerField(choices=[(0, 'Video release'), (1, "Idk, don't pick this")])),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_title', models.CharField(max_length=25)),
                ('eng_topic', models.CharField(max_length=10)),
                ('eng_description', models.TextField(max_length=350)),
                ('eng_button_text', models.CharField(max_length=15)),
                ('ukr_title', models.CharField(max_length=25)),
                ('ukr_topic', models.CharField(max_length=10)),
                ('ukr_description', models.TextField(max_length=350)),
                ('ukr_button_text', models.CharField(max_length=15)),
                ('button_link', models.TextField()),
                ('image', models.ImageField(upload_to='files/hero_images')),
                ('text_alignment', models.CharField(choices=[('left', 'Left aligned'), ('right', 'Right aligned')], max_length=5)),
            ],
        ),
    ]
