# Generated by Django 5.2.4 on 2025-08-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("stream", "Live stream"), ("trailer", "Trailer drop")],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
