# Generated by Django 5.2.4 on 2025-08-12 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_event_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date"]},
        ),
        migrations.AddField(
            model_name="event",
            name="actual_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="actual_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="last_synced",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="scheduled_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="stream_status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("live", "Live"),
                    ("completed", "Completed"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="youtube_channel_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="youtube_video_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
