# Generated by Django 5.2.4 on 2025-08-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_event_options_event_actual_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="actual_end_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="actual_start_time",
        ),
        migrations.RemoveField(
            model_name="event",
            name="stream_status",
        ),
        migrations.RemoveField(
            model_name="event",
            name="youtube_channel_id",
        ),
    ]
