# Generated by Django 5.2.4 on 2025-11-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_heroslide"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="horizontal_align",
            field=models.CharField(
                choices=[("left", "Left"), ("center", "Center"), ("right", "Right")],
                default="center",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="vertical_align",
            field=models.CharField(
                choices=[("top", "Top"), ("center", "Center"), ("bottom", "Bottom")],
                default="center",
                max_length=20,
            ),
        ),
    ]
