# Generated by Django 5.2.4 on 2025-12-24 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_user_field_if_missing(apps, schema_editor):
    StaffMember = apps.get_model("base", "StaffMember")
    table_name = StaffMember._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "user_id" in existing_columns:
        return

    field = models.OneToOneField(
        to=settings.AUTH_USER_MODEL,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="staff_profile",
    )
    field.set_attributes_from_name("user")
    schema_editor.add_field(StaffMember, field)


def remove_user_field_if_exists(apps, schema_editor):
    StaffMember = apps.get_model("base", "StaffMember")
    table_name = StaffMember._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "user_id" not in existing_columns:
        return

    field = StaffMember._meta.get_field("user")
    schema_editor.remove_field(StaffMember, field)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_staffmember_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_user_field_if_missing,
            remove_user_field_if_exists,
        )
    ]
