# Generated by Django 5.2.4 on 2025-12-24 22:35

from django.db import migrations
from django.db import models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_staffmember_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            # Check if user_id column exists, if not add it
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'base_staffmember' AND column_name = 'user_id'
                ) THEN
                    ALTER TABLE base_staffmember ADD COLUMN user_id integer;
                    ALTER TABLE base_staffmember ADD CONSTRAINT base_staffmember_user_id_eda9b3a9_fk_auth_user_id 
                        FOREIGN KEY (user_id) REFERENCES auth_user (id) DEFERRABLE INITIALLY DEFERRED;
                    CREATE UNIQUE INDEX base_staffmember_user_id_eda9b3a9_uniq ON base_staffmember (user_id);
                END IF;
            END $$;
            """,
            # Reverse SQL - remove the column if rolling back
            "ALTER TABLE base_staffmember DROP COLUMN IF EXISTS user_id CASCADE;"
        )
    ]
