# Generated by Django 5.2.4 on 2025-12-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_auto_20251224_1435"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffmember",
            name="telegram_url",
        ),
        migrations.AddField(
            model_name="staffmember",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
