# Generated by Django 5.2.4 on 2025-12-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_remove_staffmember_telegram_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="bio",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
