# Generated by Django 5.2.4 on 2026-05-16 17:43

from django.db import migrations, models


class CreateModelOrAddMissingFields(migrations.CreateModel):

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if not self.allow_migrate_model(schema_editor.connection.alias, model):
            return

        if model._meta.db_table not in schema_editor.connection.introspection.table_names():
            return super().database_forwards(app_label, schema_editor, from_state, to_state)

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(
                    cursor, model._meta.db_table
                )
            }

        for field in model._meta.local_fields:
            if field.column not in existing_columns:
                schema_editor.add_field(model, field)
                existing_columns.add(field.column)


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_staffmember_bio"),
    ]

    operations = [
        CreateModelOrAddMissingFields(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField(max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="staffmember",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="staffmember",
            name="callsign",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="internal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="portfolio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("away", "Away"),
                    ("offline", "Offline"),
                ],
                default="online",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffmember",
            name="x_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
