# Generated by Django 6.1.1 on 2026-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_contactrequest_alter_staffmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='x_url',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
