# Generated by Django 6.1.1 on 2026-09-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_staffmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
