# Generated by Django 6.1.1 on 2026-09-22 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_blogpost_author(apps, schema_editor):
    user_model = apps.get_model("auth", "User")
    blog_post_model = apps.get_model("base", "BlogPost")

    fallback_user = user_model.objects.order_by("id").first()
    if fallback_user is None:
        fallback_user = user_model.objects.create(username="system_author")

    blog_post_model.objects.filter(author__isnull=True).update(author=fallback_user)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_modpack'),
        ('frogsnet', '0022_remove_forumpost_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_blogpost_author, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
