# Generated by Django 6.1.1 on 2026-09-28 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_blogpost_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('localhost_ip', models.GenericIPAddressField(blank=True, help_text='Optional local IP address for internal use', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('server_id', models.CharField(blank=True, help_text="Crafty's server ID for fetching server details", max_length=100, null=True)),
                ('port', models.PositiveIntegerField(default=25565)),
                ('description', models.TextField(blank=True)),
                ('world_size', models.CharField(blank=True, help_text='Size of the world in MB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.CharField(blank=True, max_length=2, null=True)),
                ('is_online', models.BooleanField(default=False, help_text='Indicates if the server is currently online')),
                ('current_players', models.PositiveIntegerField(default=0, help_text='Current number of players on the server')),
                ('max_players', models.PositiveIntegerField(default=10, help_text='Maximum number of players allowed on the server')),
                ('modpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='base.modpack')),
            ],
        ),
    ]
