# Generated by ChatGPT on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_server"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="region",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=2,
                choices=[
                    ("NA", "North America"),
                    ("EU", "Europe"),
                    ("AS", "Asia"),
                    ("SA", "South America"),
                    ("AF", "Africa"),
                    ("OC", "Oceania"),
                ],
            ),
        ),
    ]
