# Generated by Django 6.1.1 on 2026-09-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_server_region_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='world_size',
            field=models.CharField(blank=True, help_text='Size of the world in MB', max_length=50, null=True),
        ),
    ]
